#!/bin/sh

set -e

VERSION=0.1.5
POSTINST=/usr/lib/dkms/common.postinst

case "$1" in
	configure)
		if [ -f $POSTINST ]; then
			"$POSTINST" ryzen_smu "$VERSION" "/usr/share/ryzen-smu" x86_64 "$2"
		fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
